# Generated by Django 5.2.1 on 2025-05-31 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialconsultas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_consultas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagocreditos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_creditos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagocreditos',
            name='paquete_creditos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.paquetecreditos'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagosuscripcion',
            name='suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='billing.suscripcion'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='tipo_suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.tiposuscripcion'),
        ),
        migrations.AddField(
            model_name='transaccioncreditos',
            name='paquete_creditos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.paquetecreditos'),
        ),
        migrations.AddField(
            model_name='transaccioncreditos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_creditos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
