# Generated by Django 5.2.1 on 2025-06-01 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('color_boton', models.CharField(default='#007cba', max_length=7)),
                ('paises_soportados', models.JSONField(default=list)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='pagocreditos',
            name='datos_pago',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paquetecreditos',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paquetecreditos',
            name='precio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='BotonPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_base', models.URLField(blank=True)),
                ('parametros_adicionales', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='botones_pago', to='billing.paquetecreditos')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.metodopago')),
            ],
            options={
                'verbose_name': 'Botón de Pago',
                'verbose_name_plural': 'Botones de Pago',
                'unique_together': {('paquete', 'metodo_pago')},
            },
        ),
        migrations.AddField(
            model_name='pagocreditos',
            name='boton_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.botonpago'),
        ),
    ]
