# Generated by Django 5.2.1 on 2025-06-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_metodopago_pagocreditos_datos_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='creditos_disponibles',
            field=models.IntegerField(default=3),
        ),
    ]
