# Generated by Django 5.2.1 on 2025-06-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_wallet_creditos_disponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='creditos_disponibles',
            field=models.IntegerField(default=0),
        ),
    ]
