# Generated by Django 5.2.1 on 2025-06-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_wallet_creditos_disponibles"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagocreditos",
            name="custom_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
