# Generated by Django 5.2.1 on 2025-05-31 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Set',
                'verbose_name_plural': 'Sets',
            },
        ),
        migrations.CreateModel(
            name='Mazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('permite_cartas_invertidas', models.BooleanField(default=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mazos', to='oraculoApi.set')),
            ],
            options={
                'verbose_name': 'Mazo',
                'verbose_name_plural': 'Mazos',
            },
        ),
        migrations.CreateModel(
            name='Tirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='tiradas/')),
                ('cantidad_cartas', models.IntegerField()),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiradas', to='oraculoApi.mazo')),
            ],
            options={
                'verbose_name': 'Tirada',
                'verbose_name_plural': 'Tiradas',
            },
        ),
        migrations.CreateModel(
            name='ItemDeTirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_posicion', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('tirada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='oraculoApi.tirada')),
            ],
            options={
                'verbose_name': 'Item de Tirada',
                'verbose_name_plural': 'Items de Tirada',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='cartas/')),
                ('significado_normal', models.TextField()),
                ('significado_invertida', models.TextField()),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='oraculoApi.mazo')),
            ],
            options={
                'verbose_name': 'Carta',
                'verbose_name_plural': 'Cartas',
                'ordering': ['numero'],
                'unique_together': {('mazo', 'numero')},
            },
        ),
    ]
