# Generated by Django 5.2.1 on 2025-05-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculoApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirada',
            name='costo',
            field=models.IntegerField(default=0),
        ),
    ]
