# Generated by Django 5.2.1 on 2025-06-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraculoApi", "0002_tirada_costo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carta",
            name="significado_invertida",
            field=models.TextField(blank=True),
        ),
    ]
